### PR TITLE
Python3 compatible

### PR DESCRIPTION
**Pull request by nickj21**
This is my first attempt at converting a python 2 module to 3, so if it's a little heavy handed just let me know.

The C extension was very straight forward. All that was required was to split the initialization hook by version and to update the type of string value type decode was using.

I used the future module to convert the python modules. This added a requirement, but makes python 2 and 3 compatibility pretty clean (from my limited experience.)

The python 3 string vs bytes got a little hairy, but managed to keep everything functioning including the log format.

### CODE REVIEW

**Comment by ahothan** [comment]
I had a quick look and the diff is not that large. 
Only concern is the drop of performance in py2.7 for the decode.

$ tox -e py27 '-k test_dec_perf --runperf'
...
         415055 function calls in 0.316 seconds

while with the original code:

$ tox -e py27 '-k test_dec_perf --runperf'
...
         115325 function calls in 0.148 seconds

So the number of functions called is much higher and the decode time is over 2x slower.
Will have to see which changes are causing that overhead.
Looks like xrange -> range in python 2.7 may contribute some.
old_div is also adding quite a bit.

Let me think about it and see if there is a way around it.

**Comment by ahothan** [comment]
I've seen some people do this to get around the xrange change:
try:
    xrange
except NameError:
    xrange = range

**Comment by nickj21** [comment]
I didn't see any performance gain by changing the range operation, but the old_div call was definitely bogging things down. I am still enforcing python3 division rules, so float vs integer division has to be explicit.

**Comment by nickj21** [comment]
I'm looking into why there is still about a 7% performance hit.

**Comment by ahothan** [comment]
if we could get within 5% hit that would be great, so looks lie your'e pretty close already.
I am fine for the xrange to range change and everything else looks good.
python 3 is not as efficient but this is not a surprise and is still pretty decent.
Thanks!

**Comment by nickj21** [comment]
I think it is good to go now. Running it locally 7% might have even been a conservative estimate, may already be in 5% range. I'll keep working on it in the background though.

**Comment by ahothan** [comment]
Just merged, excellent work! Thanks

**Pull request merged**
