### PR TITLE
Add output_percentile_distribution method

### PR DESCRIPTION
**Pull request by lebinh**
Similar to the format used in https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/AbstractHistogram.java#L1516 and usable for plotting with http://hdrhistogram.github.io/HdrHistogram/plotFiles.html

### CODE REVIEW

**Comment by ahothan** [comment]
Hi!
Thank you so much for your contribution, the code looks good...
To expedite the pull request, would you have by any chance a test code that replicates the output provided by @mpeterson0x0 ?
(check in https://github.com/HdrHistogram/HdrHistogram_py/issues/4)
If you have it could you please add the corresponding test code (pretty much a port of the corresponding test method in SimpleHistogramExample.java) to:
https://github.com/HdrHistogram/HdrHistogram_py/blob/master/test/test_hdrhistogram.py.

I think a new test function in the log category would be appropriate:

@pytest.mark.log
def test_output_percentile_distribution:

A textual diff on the output with the expected output string serving as a "PASS" would be terrific.

If you do not have time I'll do it on my next spare time (hopefully sometime next week).

**Comment by lebinh** [comment]
Thanks, I will try to find sometime to do that later this week.

**Comment by ahothan** [comment]
@lebinh, actually I looked at the java example and it uses socket calls, so probably not worth replicating as is since the results will vary from run to run.
So I'm going to pull your changes and I'll add a simple test code to complete it

**Comment by lebinh** [comment]
Yay 👍

**Pull request merged**
